### Extracting Text from PDF

In [1]:
# !pip install pypdf

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.1.2 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("../advs.pdf")
pages = loader.load_and_split()

In [6]:
pages[0].page_content

'The Adventures of Sherlock Holmes\nArthur Conan Doyle'

In [8]:
corpus = ""
for page in pages:
    corpus += page.page_content
print(corpus)

The Adventures of Sherlock Holmes
Arthur Conan DoyleThis text is provided to you “as-is” without any warranty. No warranties of any kind, expressed or implied, are made to you as to the text
or any medium it may be on, including but not limited to warranties of merchantablity or fitness for a particular purpose.
This text was formatted from various free ASCII and HTML variants. See http:/ /sherlock-holm.es for an electronic form of this text and
additional information about it.
This text comes from the collection’s version 3.1.Table of contents
A Scandal in Bohemia . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1
The Red-Headed League . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 17
A Case of Identity . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 31
The Boscombe Valley Mystery . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 

In [19]:
letters = ""
# letters += str(sorted((set(corpus))))
print(sorted(set(corpus)))
for i in sorted(set(corpus)):
    letters += i
print(letters)
print(len(letters))

[' ', '!', '&', '(', ')', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'Y', 'Z', '[', ']', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '£', '´', 'ˆ', '—', '‘', '’', '“', '”', 'fi', 'fl']
 !&(),-./0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWYZ[]`abcdefghijklmnopqrstuvwxyz£´ˆ—‘’“”fifl
86


In [18]:
corpus = corpus.replace("\n","")
corpus

'The Adventures of Sherlock HolmesArthur Conan DoyleThis text is provided to you “as-is” without any warranty. No warranties of any kind, expressed or implied, are made to you as to the textor any medium it may be on, including but not limited to warranties of merchantablity or fitness for a particular purpose.This text was formatted from various free ASCII and HTML variants. See http:/ /sherlock-holm.es for an electronic form of this text andadditional information about it.This text comes from the collection’s version 3.1.Table of contentsA Scandal in Bohemia . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1The Red-Headed League . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 17A Case of Identity . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 31The Boscombe Valley Mystery . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 

In [21]:
text_file = open("../advs.txt", "w", encoding="utf-8")
text_file.write(corpus)
text_file.close()

In [22]:
stoi = {ch:i for i,ch in enumerate(letters)} # String to Index (of letters)
itos = {i:ch for i,ch in enumerate(letters)} # Index to String
encoder = lambda s: [stoi[c] for c in s]
decoder = lambda l: "".join([itos[i] for i in l])

print(encoder("Hello"))
print(decoder(encoder("Hello")))

[29, 54, 61, 61, 64]
Hello


In [23]:
# Encoding the entire dataset and store it to a Tensor
import torch
data = torch.tensor(encoder(corpus),dtype = torch.long)
print(data.shape,data.dtype)
print(data[:1000])

torch.Size([572854]) torch.int64
tensor([41, 57, 54,  0, 22, 53, 71, 54, 63, 69, 70, 67, 54, 68,  0, 64, 55,  0,
        40, 57, 54, 67, 61, 64, 52, 60,  0, 29, 64, 61, 62, 54, 68, 22, 67, 69,
        57, 70, 67,  0, 24, 64, 63, 50, 63,  0, 25, 64, 74, 61, 54, 41, 57, 58,
        68,  0, 69, 54, 73, 69,  0, 58, 68,  0, 65, 67, 64, 71, 58, 53, 54, 53,
         0, 69, 64,  0, 74, 64, 70,  0, 82, 50, 68,  6, 58, 68, 83,  0, 72, 58,
        69, 57, 64, 70, 69,  0, 50, 63, 74,  0, 72, 50, 67, 67, 50, 63, 69, 74,
         7,  0, 35, 64,  0, 72, 50, 67, 67, 50, 63, 69, 58, 54, 68,  0, 64, 55,
         0, 50, 63, 74,  0, 60, 58, 63, 53,  5,  0, 54, 73, 65, 67, 54, 68, 68,
        54, 53,  0, 64, 67,  0, 58, 62, 65, 61, 58, 54, 53,  5,  0, 50, 67, 54,
         0, 62, 50, 53, 54,  0, 69, 64,  0, 74, 64, 70,  0, 50, 68,  0, 69, 64,
         0, 69, 57, 54,  0, 69, 54, 73, 69, 64, 67,  0, 50, 63, 74,  0, 62, 54,
        53, 58, 70, 62,  0, 58, 69,  0, 62, 50, 74,  0, 51, 54,  0, 64, 63,  5,
       

In [25]:
n = int(0.9 * len(data)) # 90% = Train, 10% = validation
train_data = data[:n]
val_data = data[n:]
# print(val_data)

tensor([ 0, 74, 64,  ..., 10, 14, 17])


In [26]:
block_size = 8
train_data[:block_size]

tensor([41, 57, 54,  0, 22, 53, 71, 54])

In [27]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1] # Prev. tokens
    target = y[t] # Expected next token
    print(f"Input : {context}, then Target : {target}")

Input : tensor([41]), then Target : 57
Input : tensor([41, 57]), then Target : 54
Input : tensor([41, 57, 54]), then Target : 0
Input : tensor([41, 57, 54,  0]), then Target : 22
Input : tensor([41, 57, 54,  0, 22]), then Target : 53
Input : tensor([41, 57, 54,  0, 22, 53]), then Target : 71
Input : tensor([41, 57, 54,  0, 22, 53, 71]), then Target : 54
Input : tensor([41, 57, 54,  0, 22, 53, 71, 54]), then Target : 63


In [28]:
torch.manual_seed(1337) # Random number generator
batch_size = 4
block_size = 8
def get_batch(split): 
    # Generates Train or Validation Datasets
    data = train_data if split == "train" else val_data # Load Train/validate data
    ix = torch.randint(len(data)-block_size,(batch_size,)) # Random Indices
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    # x : input sequence, y : target sequence , each of length block_size
    return x,y

xb,yb = get_batch("train")
print("Inputs : ")
print(xb.shape)
print("Targets : ")
print(yb.shape)
print(yb)

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b,:t+1]
        target = yb[b,t]
        print(f"Input : {context.tolist()}, then Target is : {target}")


Inputs : 
torch.Size([4, 8])
Targets : 
torch.Size([4, 8])
tensor([[ 5,  0, 30,  0, 50, 62,  0, 53],
        [69, 54, 67,  0, 69, 57, 54, 58],
        [ 0, 64, 65, 54, 63,  0, 57, 58],
        [53,  0, 69, 64,  0, 72, 50, 67]])
Input : [64], then Target is : 5
Input : [64, 5], then Target is : 0
Input : [64, 5, 0], then Target is : 30
Input : [64, 5, 0, 30], then Target is : 0
Input : [64, 5, 0, 30, 0], then Target is : 50
Input : [64, 5, 0, 30, 0, 50], then Target is : 62
Input : [64, 5, 0, 30, 0, 50, 62], then Target is : 0
Input : [64, 5, 0, 30, 0, 50, 62, 0], then Target is : 53
Input : [55], then Target is : 69
Input : [55, 69], then Target is : 54
Input : [55, 69, 54], then Target is : 67
Input : [55, 69, 54, 67], then Target is : 0
Input : [55, 69, 54, 67, 0], then Target is : 69
Input : [55, 69, 54, 67, 0, 69], then Target is : 57
Input : [55, 69, 54, 67, 0, 69, 57], then Target is : 54
Input : [55, 69, 54, 67, 0, 69, 57, 54], then Target is : 58
Input : [74], then Target is : 

In [29]:
print(xb) # Input to transformer

tensor([[64,  5,  0, 30,  0, 50, 62,  0],
        [55, 69, 54, 67,  0, 69, 57, 54],
        [74,  0, 64, 65, 54, 63,  0, 57],
        [54, 53,  0, 69, 64,  0, 72, 50]])


In [34]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    def __init__(self,vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size,vocab_size)
    def forward(self,idx,targets):
        logits = self.token_embedding_table(idx) # (B, T, C) : 
        loss = F.cross_entropy(logits,targets)
        return logits

vocab_size = len(letters)
m = BigramLanguageModel(vocab_size)
B,T,C = logits.shape
logits = logits.view(B*T,C)
targets = targets.view(B*T)
logits,loss = m(xb,yb)
print(logits.shape)
# print(output)

RuntimeError: Expected target size [4, 86], got [4, 8]